# PostgreSQL Primary Configuration
listen_addresses = '*'
wal_level = replica
max_wal_senders = 3
max_replication_slots = 3
synchronous_commit = off
archive_mode = on
archive_command = 'cd .'
max_wal_size = 1GB
min_wal_size = 80MB
checkpoint_completion_target = 0.7
wal_buffers = 16MB
shared_preload_libraries = 'pg_stat_statements'
